M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu18.04.1} date ven. 09 sept. 2022 12:05:54 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-09T12:05:54+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu18.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X160.465Y-74.295
T0
M30
